apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: simplest
spec:
  image: otel/opentelemetry-collector-contrib:0.96.0
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      batch:
        timeout: 5s
        send_batch_size: 100000

    exporters:
      clickhouse:
        endpoint: tcp://clickhouse-simple-01.default.svc.cluster.local:9000?dial_timeout=10s&compress=lz4
        username: test_user
        password: test_password
        database: otel
        logs_table_name: otel_logs
        traces_table_name: otel_traces
        metrics_table_name: otel_metrics
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 300s

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [ batch ]
          exporters: [ clickhouse ]
        logs:
          receivers: [otlp]
          processors: [ batch ]
          exporters: [ clickhouse ]
        traces:
          receivers: [otlp]
          processors: [ batch ]
          exporters: [ clickhouse ]